name: Bionic

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:bionic
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1
    - name: install ansible
      run: |
        apt-get update
        apt-get install software-properties-common -y
        apt-add-repository --yes --update ppa:ansible/ansible
        apt-get install ansible python-apt -y
    - name: run ansible
      run : ansible-playbook ./build_ppl.yaml
